services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    container_name: nuxt3-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
