// This file is auto-generated by @hey-api/openapi-ts

export type AnswerRequest = {
    choice: number;
};

export type AnswerResponse = {
    result: string;
    correct: boolean;
};

export type BaseUuid = {
    uuid: string;
};

export type BasicDepartment = {
    uuid: string;
    name: string;
};

export type BasicLocation = {
    city: string | null;
};

export type BasicRoom = {
    uuid: string;
    name: string;
};

export type CityDetailsResponse = {
    city_name: string;
    city_name_inflect: string;
    lat: number;
    lon: number;
    lat_min: number;
    lon_min: number;
    lat_max: number;
    lon_max: number;
    population: number;
    importance: number;
    category?: string | null;
    region?: string | null;
    country?: string | null;
    seo_title?: string | null;
    seo_description?: string | null;
};

export type CompaniesPaginated = {
    data: Array<CompanyIndexResponse>;
    count: number;
    limit: number;
    offset: number;
};

export type CompanyAdd = {
    name: string;
    brand?: string | null;
    gov_id: string;
    gov_id_type?: string | null;
    website?: string | null;
    email?: string | null;
    phone?: string | null;
    location: LocationAdd;
};

export type CompanyEdit = {
    name?: string | null;
    brand?: string | null;
    gov_id?: string | null;
    gov_id_type?: string | null;
    place_id?: string | null;
    website?: string | null;
    email?: string | null;
    phone?: string | null;
    location?: LocationEdit | null;
};

export type CompanyIndexResponse = {
    uuid: string;
    name: string;
    verified_at: string | null;
    location: BasicLocation | null;
    departments: Array<BasicDepartment> | null;
    rooms: Array<BasicRoom> | null;
};

export type CurrentPuzzleResponse = {
    scenario: string;
    base_hint: string;
    options: Array<Option>;
    correct: number;
    result: string;
    wrong_feedback: Array<WrongFeedback>;
    current_puzzle: number;
};

export type DepartmentAdd = {
    company_uuid: string;
    name: string;
    location?: LocationAdd | null;
};

export type DepartmentEdit = {
    name?: string | null;
    location?: LocationEdit | null;
};

export type GameOutro = {
    outro: string;
};

export type GameStart = {
    theme: string;
    description: string;
    difficulty: string;
    category: string;
    occasion: string;
    email?: string | null;
};

export type GameStartResponse = {
    uuid: string;
    token: string;
    intro: string;
    created_at: string;
};

export type GeoNameAdd = {
    name: string;
    lang: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type IntroResponse = {
    theme: string;
    intro: string;
};

export type Location = {
    street_address: string;
    city: string;
    state_province?: string | null;
    postal_code?: string | null;
    country: string;
    located_in?: string | null;
    lat?: number | null;
    lon?: number | null;
};

export type LocationAdd = {
    street_name?: string | null;
    street_number?: string | null;
    city: string;
    state_province?: string | null;
    postal_code?: string | null;
    country: string;
    located_in?: string | null;
    lat?: number | null;
    lon?: number | null;
};

export type LocationEdit = {
    uuid?: string | null;
    street_address?: string | null;
    city?: string | null;
    state_province?: string | null;
    postal_code?: string | null;
    country: string;
    located_in?: string | null;
    lat?: number | null;
    lon?: number | null;
};

export type Option = {
    number: number;
    text: string;
};

export type PlaceAdd = {
    lat: number | string | null;
    lon: number | string | null;
    lat_min: number | string | null;
    lat_max: number | string | null;
    lon_min: number | string | null;
    lon_max: number | string | null;
    population: number | null;
    importance: number | null;
    category: string;
    region: string | null;
    country: string | null;
    geo_names: Array<GeoNameAdd>;
};

export type ReviewRequest = {
    text: string;
    score: number;
};

export type RoomAdd = {
    name: string;
    company_uuid: string;
    department_uuid?: string | null;
    price_from?: number | null;
    game_duration?: number | null;
    players_min?: number | null;
    players_max?: number | null;
    reservation_url?: string | null;
    lm_id?: string | null;
    mt_id?: string | null;
    location?: LocationAdd | null;
    translation: Array<TranslationAdd>;
    supported_languages: Array<string>;
};

export type RoomIndexResponse = {
    uuid: string;
    url_slug: string;
    reservation_url: string | null;
    players_min: number | null;
    players_max: number | null;
    price_from: number | null;
    game_duration: number | null;
    location: Location;
    translation?: RoomTranslation | null;
};

export type RoomTranslation = {
    lang: string;
    title: string;
    lead: string;
    description: string;
};

export type TranslationAdd = {
    lang: string;
    title: string;
    lead?: string | null;
    description?: string | null;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type WrongFeedback = {
    number: number;
    feedback: string;
};

export type GetRoomsCountRoomsCountGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rooms/count';
};

export type GetRoomsCountRoomsCountGetResponses = {
    /**
     * Successful Response
     */
    200: number;
};

export type GetRoomsCountRoomsCountGetResponse = GetRoomsCountRoomsCountGetResponses[keyof GetRoomsCountRoomsCountGetResponses];

export type GetRoomsNearbyRoomsNearbyCityAsciiNameGetData = {
    body?: never;
    path: {
        city_ascii_name: string;
    };
    query?: never;
    url: '/rooms/nearby/{city_ascii_name}';
};

export type GetRoomsNearbyRoomsNearbyCityAsciiNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRoomsNearbyRoomsNearbyCityAsciiNameGetError = GetRoomsNearbyRoomsNearbyCityAsciiNameGetErrors[keyof GetRoomsNearbyRoomsNearbyCityAsciiNameGetErrors];

export type GetRoomsNearbyRoomsNearbyCityAsciiNameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteRoomRoomsRoomUuidDeleteData = {
    body?: never;
    path: {
        room_uuid: string;
    };
    query?: never;
    url: '/rooms/{room_uuid}';
};

export type DeleteRoomRoomsRoomUuidDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRoomRoomsRoomUuidDeleteError = DeleteRoomRoomsRoomUuidDeleteErrors[keyof DeleteRoomRoomsRoomUuidDeleteErrors];

export type DeleteRoomRoomsRoomUuidDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRoomRoomsRoomUuidDeleteResponse = DeleteRoomRoomsRoomUuidDeleteResponses[keyof DeleteRoomRoomsRoomUuidDeleteResponses];

export type GetRoomByUuidRoomsRoomUuidGetData = {
    body?: never;
    path: {
        room_uuid: string;
    };
    query?: never;
    url: '/rooms/{room_uuid}';
};

export type GetRoomByUuidRoomsRoomUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRoomByUuidRoomsRoomUuidGetError = GetRoomByUuidRoomsRoomUuidGetErrors[keyof GetRoomByUuidRoomsRoomUuidGetErrors];

export type GetRoomByUuidRoomsRoomUuidGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetData = {
    body?: never;
    path: {
        language: string;
        room_url_slug: string;
    };
    query?: never;
    url: '/rooms/url/{language}/{room_url_slug}';
};

export type RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetError = RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetErrors[keyof RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetErrors];

export type RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetResponses = {
    /**
     * Successful Response
     */
    200: RoomIndexResponse;
};

export type RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetResponse = RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetResponses[keyof RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetResponses];

export type RoomsByLocationRoomsUrlLanguagePlaceLocationGetData = {
    body?: never;
    path: {
        language: string;
        location: string;
    };
    query?: {
        limit?: number;
        offset?: number;
        field?: 'name' | 'created_at';
        order?: 'asc' | 'desc';
    };
    url: '/rooms/url/{language}/place/{location}';
};

export type RoomsByLocationRoomsUrlLanguagePlaceLocationGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsByLocationRoomsUrlLanguagePlaceLocationGetError = RoomsByLocationRoomsUrlLanguagePlaceLocationGetErrors[keyof RoomsByLocationRoomsUrlLanguagePlaceLocationGetErrors];

export type RoomsByLocationRoomsUrlLanguagePlaceLocationGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateRoomRoomsPostData = {
    body: RoomAdd;
    path?: never;
    query?: never;
    url: '/rooms';
};

export type CreateRoomRoomsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRoomRoomsPostError = CreateRoomRoomsPostErrors[keyof CreateRoomRoomsPostErrors];

export type CreateRoomRoomsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPlacesWithRoomsPlacesGetData = {
    body?: never;
    path?: never;
    query?: {
        country?: string | null;
    };
    url: '/places';
};

export type GetPlacesWithRoomsPlacesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPlacesWithRoomsPlacesGetError = GetPlacesWithRoomsPlacesGetErrors[keyof GetPlacesWithRoomsPlacesGetErrors];

export type GetPlacesWithRoomsPlacesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddRoomPlacesPostData = {
    body: PlaceAdd;
    path?: never;
    query?: never;
    url: '/places';
};

export type AddRoomPlacesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddRoomPlacesPostError = AddRoomPlacesPostErrors[keyof AddRoomPlacesPostErrors];

export type AddRoomPlacesPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AddRoomPlacesPostResponse = AddRoomPlacesPostResponses[keyof AddRoomPlacesPostResponses];

export type GetCityDetailsPlacesCityAsciiNameGetData = {
    body?: never;
    path: {
        city_ascii_name: string;
    };
    query: {
        language: string;
        country: string;
    };
    url: '/places/{city_ascii_name}';
};

export type GetCityDetailsPlacesCityAsciiNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCityDetailsPlacesCityAsciiNameGetError = GetCityDetailsPlacesCityAsciiNameGetErrors[keyof GetCityDetailsPlacesCityAsciiNameGetErrors];

export type GetCityDetailsPlacesCityAsciiNameGetResponses = {
    /**
     * Successful Response
     */
    200: CityDetailsResponse;
};

export type GetCityDetailsPlacesCityAsciiNameGetResponse = GetCityDetailsPlacesCityAsciiNameGetResponses[keyof GetCityDetailsPlacesCityAsciiNameGetResponses];

export type GetNearbyCitiesPlacesNearbyCityCityAsciiNameGetData = {
    body?: never;
    path: {
        city_ascii_name: string;
    };
    query?: never;
    url: '/places/nearby_city/{city_ascii_name}';
};

export type GetNearbyCitiesPlacesNearbyCityCityAsciiNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetNearbyCitiesPlacesNearbyCityCityAsciiNameGetError = GetNearbyCitiesPlacesNearbyCityCityAsciiNameGetErrors[keyof GetNearbyCitiesPlacesNearbyCityCityAsciiNameGetErrors];

export type GetNearbyCitiesPlacesNearbyCityCityAsciiNameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRoomsByLocationPlacesRoomsLocationNameGetData = {
    body?: never;
    path: {
        location_name: string;
    };
    query?: {
        language?: string | null;
    };
    url: '/places/rooms/{location_name}';
};

export type GetRoomsByLocationPlacesRoomsLocationNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRoomsByLocationPlacesRoomsLocationNameGetError = GetRoomsByLocationPlacesRoomsLocationNameGetErrors[keyof GetRoomsByLocationPlacesRoomsLocationNameGetErrors];

export type GetRoomsByLocationPlacesRoomsLocationNameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRoomsByGeolocationPlacesRoomsGeoipGetData = {
    body?: never;
    headers?: {
        'x-forwarded-for'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/places/rooms/geoip';
};

export type GetRoomsByGeolocationPlacesRoomsGeoipGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRoomsByGeolocationPlacesRoomsGeoipGetError = GetRoomsByGeolocationPlacesRoomsGeoipGetErrors[keyof GetRoomsByGeolocationPlacesRoomsGeoipGetErrors];

export type GetRoomsByGeolocationPlacesRoomsGeoipGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCompaniesCompaniesGetData = {
    body?: never;
    path?: never;
    query?: {
        search?: string | null;
        limit?: number;
        offset?: number;
        field?: 'name' | 'created_at';
        order?: 'asc' | 'desc';
    };
    url: '/companies';
};

export type GetCompaniesCompaniesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCompaniesCompaniesGetError = GetCompaniesCompaniesGetErrors[keyof GetCompaniesCompaniesGetErrors];

export type GetCompaniesCompaniesGetResponses = {
    /**
     * Successful Response
     */
    200: CompaniesPaginated;
};

export type GetCompaniesCompaniesGetResponse = GetCompaniesCompaniesGetResponses[keyof GetCompaniesCompaniesGetResponses];

export type CreateCompanyCompaniesPostData = {
    body: CompanyAdd;
    path?: never;
    query?: never;
    url: '/companies';
};

export type CreateCompanyCompaniesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCompanyCompaniesPostError = CreateCompanyCompaniesPostErrors[keyof CreateCompanyCompaniesPostErrors];

export type CreateCompanyCompaniesPostResponses = {
    /**
     * Successful Response
     */
    201: BaseUuid;
};

export type CreateCompanyCompaniesPostResponse = CreateCompanyCompaniesPostResponses[keyof CreateCompanyCompaniesPostResponses];

export type DeleteCompanyCompaniesCompanyUuidDeleteData = {
    body?: never;
    path: {
        company_uuid: string;
    };
    query?: never;
    url: '/companies/{company_uuid}';
};

export type DeleteCompanyCompaniesCompanyUuidDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCompanyCompaniesCompanyUuidDeleteError = DeleteCompanyCompaniesCompanyUuidDeleteErrors[keyof DeleteCompanyCompaniesCompanyUuidDeleteErrors];

export type DeleteCompanyCompaniesCompanyUuidDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCompanyCompaniesCompanyUuidDeleteResponse = DeleteCompanyCompaniesCompanyUuidDeleteResponses[keyof DeleteCompanyCompaniesCompanyUuidDeleteResponses];

export type GetCompanyByUuidCompaniesCompanyUuidGetData = {
    body?: never;
    path: {
        company_uuid: string;
    };
    query?: never;
    url: '/companies/{company_uuid}';
};

export type GetCompanyByUuidCompaniesCompanyUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCompanyByUuidCompaniesCompanyUuidGetError = GetCompanyByUuidCompaniesCompanyUuidGetErrors[keyof GetCompanyByUuidCompaniesCompanyUuidGetErrors];

export type GetCompanyByUuidCompaniesCompanyUuidGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateCompanyCompaniesCompanyUuidPatchData = {
    body: CompanyEdit;
    path: {
        company_uuid: string;
    };
    query?: never;
    url: '/companies/{company_uuid}';
};

export type UpdateCompanyCompaniesCompanyUuidPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCompanyCompaniesCompanyUuidPatchError = UpdateCompanyCompaniesCompanyUuidPatchErrors[keyof UpdateCompanyCompaniesCompanyUuidPatchErrors];

export type UpdateCompanyCompaniesCompanyUuidPatchResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UpdateCompanyCompaniesCompanyUuidPatchResponse = UpdateCompanyCompaniesCompanyUuidPatchResponses[keyof UpdateCompanyCompaniesCompanyUuidPatchResponses];

export type GetCompanyDepartmentsCompaniesCompanyUuidDepartmentsGetData = {
    body?: never;
    path: {
        company_uuid: string;
    };
    query?: never;
    url: '/companies/{company_uuid}/departments';
};

export type GetCompanyDepartmentsCompaniesCompanyUuidDepartmentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCompanyDepartmentsCompaniesCompanyUuidDepartmentsGetError = GetCompanyDepartmentsCompaniesCompanyUuidDepartmentsGetErrors[keyof GetCompanyDepartmentsCompaniesCompanyUuidDepartmentsGetErrors];

export type GetCompanyDepartmentsCompaniesCompanyUuidDepartmentsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCompanyLocationsCompaniesCompanyUuidLocationsGetData = {
    body?: never;
    path: {
        company_uuid: string;
    };
    query?: never;
    url: '/companies/{company_uuid}/locations';
};

export type GetCompanyLocationsCompaniesCompanyUuidLocationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCompanyLocationsCompaniesCompanyUuidLocationsGetError = GetCompanyLocationsCompaniesCompanyUuidLocationsGetErrors[keyof GetCompanyLocationsCompaniesCompanyUuidLocationsGetErrors];

export type GetCompanyLocationsCompaniesCompanyUuidLocationsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteData = {
    body?: never;
    path: {
        department_uuid: string;
    };
    query?: never;
    url: '/companies/departments/{department_uuid}';
};

export type DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteError = DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteErrors[keyof DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteErrors];

export type DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteResponse = DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteResponses[keyof DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteResponses];

export type GetDepartmentCompaniesDepartmentsDepartmentUuidGetData = {
    body?: never;
    path: {
        department_uuid: string;
    };
    query?: never;
    url: '/companies/departments/{department_uuid}';
};

export type GetDepartmentCompaniesDepartmentsDepartmentUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDepartmentCompaniesDepartmentsDepartmentUuidGetError = GetDepartmentCompaniesDepartmentsDepartmentUuidGetErrors[keyof GetDepartmentCompaniesDepartmentsDepartmentUuidGetErrors];

export type GetDepartmentCompaniesDepartmentsDepartmentUuidGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchData = {
    body: DepartmentEdit;
    path: {
        department_uuid: string;
    };
    query?: never;
    url: '/companies/departments/{department_uuid}';
};

export type UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchError = UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchErrors[keyof UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchErrors];

export type UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchResponse = UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchResponses[keyof UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchResponses];

export type CreateDepartmentCompaniesDepartmentsPostData = {
    body: DepartmentAdd;
    path?: never;
    query?: never;
    url: '/companies/departments';
};

export type CreateDepartmentCompaniesDepartmentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDepartmentCompaniesDepartmentsPostError = CreateDepartmentCompaniesDepartmentsPostErrors[keyof CreateDepartmentCompaniesDepartmentsPostErrors];

export type CreateDepartmentCompaniesDepartmentsPostResponses = {
    /**
     * Successful Response
     */
    200: BaseUuid;
};

export type CreateDepartmentCompaniesDepartmentsPostResponse = CreateDepartmentCompaniesDepartmentsPostResponses[keyof CreateDepartmentCompaniesDepartmentsPostResponses];

export type StartGameGamesStartPostData = {
    body: GameStart;
    path?: never;
    query?: never;
    url: '/games/start';
};

export type StartGameGamesStartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartGameGamesStartPostError = StartGameGamesStartPostErrors[keyof StartGameGamesStartPostErrors];

export type StartGameGamesStartPostResponses = {
    /**
     * Successful Response
     */
    200: GameStartResponse;
};

export type StartGameGamesStartPostResponse = StartGameGamesStartPostResponses[keyof StartGameGamesStartPostResponses];

export type GetIntroGamesIntroGameUuidGetData = {
    body?: never;
    headers?: {
        'x-forwarded-for'?: string | null;
    };
    path: {
        game_uuid: string;
    };
    query?: never;
    url: '/games/intro/{game_uuid}';
};

export type GetIntroGamesIntroGameUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIntroGamesIntroGameUuidGetError = GetIntroGamesIntroGameUuidGetErrors[keyof GetIntroGamesIntroGameUuidGetErrors];

export type GetIntroGamesIntroGameUuidGetResponses = {
    /**
     * Successful Response
     */
    200: IntroResponse;
};

export type GetIntroGamesIntroGameUuidGetResponse = GetIntroGamesIntroGameUuidGetResponses[keyof GetIntroGamesIntroGameUuidGetResponses];

export type GetPuzzleGamesPuzzleGameUuidGetData = {
    body?: never;
    path: {
        game_uuid: string;
    };
    query?: never;
    url: '/games/puzzle/{game_uuid}';
};

export type GetPuzzleGamesPuzzleGameUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPuzzleGamesPuzzleGameUuidGetError = GetPuzzleGamesPuzzleGameUuidGetErrors[keyof GetPuzzleGamesPuzzleGameUuidGetErrors];

export type GetPuzzleGamesPuzzleGameUuidGetResponses = {
    /**
     * Successful Response
     */
    200: CurrentPuzzleResponse;
};

export type GetPuzzleGamesPuzzleGameUuidGetResponse = GetPuzzleGamesPuzzleGameUuidGetResponses[keyof GetPuzzleGamesPuzzleGameUuidGetResponses];

export type SubmitAnswerGamesAnswerGameUuidPostData = {
    body: AnswerRequest;
    path: {
        game_uuid: string;
    };
    query?: never;
    url: '/games/answer/{game_uuid}';
};

export type SubmitAnswerGamesAnswerGameUuidPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitAnswerGamesAnswerGameUuidPostError = SubmitAnswerGamesAnswerGameUuidPostErrors[keyof SubmitAnswerGamesAnswerGameUuidPostErrors];

export type SubmitAnswerGamesAnswerGameUuidPostResponses = {
    /**
     * Successful Response
     */
    200: AnswerResponse;
};

export type SubmitAnswerGamesAnswerGameUuidPostResponse = SubmitAnswerGamesAnswerGameUuidPostResponses[keyof SubmitAnswerGamesAnswerGameUuidPostResponses];

export type GetEndingGamesEndingGameUuidGetData = {
    body?: never;
    path: {
        game_uuid: string;
    };
    query?: never;
    url: '/games/ending/{game_uuid}';
};

export type GetEndingGamesEndingGameUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEndingGamesEndingGameUuidGetError = GetEndingGamesEndingGameUuidGetErrors[keyof GetEndingGamesEndingGameUuidGetErrors];

export type GetEndingGamesEndingGameUuidGetResponses = {
    /**
     * Successful Response
     */
    200: GameOutro;
};

export type GetEndingGamesEndingGameUuidGetResponse = GetEndingGamesEndingGameUuidGetResponses[keyof GetEndingGamesEndingGameUuidGetResponses];

export type AddReviewGamesReviewGameUuidPostData = {
    body: ReviewRequest;
    path: {
        game_uuid: string;
    };
    query?: never;
    url: '/games/review/{game_uuid}';
};

export type AddReviewGamesReviewGameUuidPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddReviewGamesReviewGameUuidPostError = AddReviewGamesReviewGameUuidPostErrors[keyof AddReviewGamesReviewGameUuidPostErrors];

export type AddReviewGamesReviewGameUuidPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AddReviewGamesReviewGameUuidPostResponse = AddReviewGamesReviewGameUuidPostResponses[keyof AddReviewGamesReviewGameUuidPostResponses];

export type LoactionsSitemapSeoSitemapGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/seo/sitemap';
};

export type LoactionsSitemapSeoSitemapGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetFirstUnverifiedCompanyCcCompanyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cc/company';
};

export type GetFirstUnverifiedCompanyCcCompanyGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://localhost:5000' | (string & {});
};