// This file is auto-generated by @hey-api/openapi-ts

/**
 * AnswerRequest
 */
export type AnswerRequest = {
    /**
     * Choice
     */
    choice: number;
};

/**
 * AnswerResponse
 */
export type AnswerResponse = {
    /**
     * Result
     */
    result: string;
    /**
     * Correct
     */
    correct: boolean;
};

/**
 * BaseUuid
 */
export type BaseUuid = {
    /**
     * Uuid
     */
    uuid: string;
};

/**
 * BasicDepartment
 */
export type BasicDepartment = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * BasicLanguage
 */
export type BasicLanguage = {
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
};

/**
 * BasicLocation
 */
export type BasicLocation = {
    /**
     * City
     */
    city: string | null;
};

/**
 * BasicRoom
 */
export type BasicRoom = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Active
     */
    active: boolean;
};

/**
 * CityDetailsResponse
 */
export type CityDetailsResponse = {
    /**
     * City Name
     */
    city_name: string;
    /**
     * City Name Inflect
     */
    city_name_inflect: string;
    /**
     * Lat
     */
    lat: number;
    /**
     * Lon
     */
    lon: number;
    /**
     * Lat Min
     */
    lat_min: number;
    /**
     * Lon Min
     */
    lon_min: number;
    /**
     * Lat Max
     */
    lat_max: number;
    /**
     * Lon Max
     */
    lon_max: number;
    /**
     * Population
     */
    population: number;
    /**
     * Importance
     */
    importance: number;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Region
     */
    region?: string | null;
    /**
     * Country
     */
    country?: string | null;
    /**
     * Seo Title
     */
    seo_title?: string | null;
    /**
     * Seo Description
     */
    seo_description?: string | null;
};

/**
 * CompaniesPaginated
 */
export type CompaniesPaginated = {
    /**
     * Data
     */
    data: Array<CompanyIndexResponse>;
    /**
     * Count
     */
    count: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * CompanyAdd
 */
export type CompanyAdd = {
    /**
     * Name
     */
    name: string;
    /**
     * Brand
     */
    brand?: string | null;
    /**
     * Gov Id
     */
    gov_id: string;
    /**
     * Gov Id Type
     */
    gov_id_type?: string | null;
    /**
     * Website
     */
    website?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    location: LocationAdd;
};

/**
 * CompanyEdit
 */
export type CompanyEdit = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Brand
     */
    brand?: string | null;
    /**
     * Gov Id
     */
    gov_id?: string | null;
    /**
     * Gov Id Type
     */
    gov_id_type?: string | null;
    /**
     * Place Id
     */
    place_id?: string | null;
    /**
     * Website
     */
    website?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Verified At
     */
    verified_at?: string | null;
    location?: LocationEdit | null;
};

/**
 * CompanyIndexResponse
 */
export type CompanyIndexResponse = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Verified At
     */
    verified_at: string | null;
    location: BasicLocation | null;
    /**
     * Departments
     */
    departments: Array<BasicDepartment> | null;
    /**
     * Rooms
     */
    rooms: Array<BasicRoom> | null;
};

/**
 * ContactAdd
 */
export type ContactAdd = {
    /**
     * Company Uuid
     */
    company_uuid: string;
    /**
     * Department Uuid
     */
    department_uuid?: string | null;
    type: ContactType;
    /**
     * Value
     */
    value: string;
    /**
     * Country Code
     */
    country_code?: string | null;
    /**
     * Is Primary
     */
    is_primary?: boolean;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ContactType
 */
export type ContactType = 'phone' | 'email' | 'telegram' | 'whatsapp' | 'viber' | 'facebook';

/**
 * CurrentPuzzleResponse
 */
export type CurrentPuzzleResponse = {
    /**
     * Scenario
     */
    scenario: string;
    /**
     * Base Hint
     */
    base_hint: string;
    /**
     * Options
     */
    options: Array<Option>;
    /**
     * Correct
     */
    correct: number;
    /**
     * Result
     */
    result: string;
    /**
     * Wrong Feedback
     */
    wrong_feedback: Array<WrongFeedback>;
    /**
     * Current Puzzle
     */
    current_puzzle: number;
};

/**
 * DepartmentAdd
 */
export type DepartmentAdd = {
    /**
     * Company Uuid
     */
    company_uuid: string;
    /**
     * Name
     */
    name: string;
    location?: LocationAdd | null;
};

/**
 * DepartmentEdit
 */
export type DepartmentEdit = {
    /**
     * Name
     */
    name?: string | null;
    location?: LocationEdit | null;
};

/**
 * FearLevel
 */
export type FearLevel = 'none' | 'spooky' | 'tense' | 'scary' | 'terrifying';

/**
 * GameDifficulty
 */
export type GameDifficulty = 'intro' | 'beginner' | 'intermediate' | 'advanced' | 'expert';

/**
 * GameOutro
 */
export type GameOutro = {
    /**
     * Outro
     */
    outro: string;
};

/**
 * GameStart
 */
export type GameStart = {
    /**
     * Theme
     */
    theme: string;
    /**
     * Description
     */
    description: string;
    /**
     * Difficulty
     */
    difficulty: string;
    /**
     * Category
     */
    category: string;
    /**
     * Occasion
     */
    occasion: string;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * GameStartResponse
 */
export type GameStartResponse = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Token
     */
    token: string;
    /**
     * Intro
     */
    intro: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * GeoNameAdd
 */
export type GeoNameAdd = {
    /**
     * Name
     */
    name: string;
    /**
     * Lang
     */
    lang: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IntroResponse
 */
export type IntroResponse = {
    /**
     * Theme
     */
    theme: string;
    /**
     * Intro
     */
    intro: string;
};

/**
 * Location
 */
export type Location = {
    /**
     * Street Name
     */
    street_name: string | null;
    /**
     * Street Number
     */
    street_number: string | null;
    /**
     * City
     */
    city: string;
    /**
     * State Province
     */
    state_province?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * Country
     */
    country: string;
    /**
     * Located In
     */
    located_in?: string | null;
    /**
     * Lat
     */
    lat?: number | null;
    /**
     * Lon
     */
    lon?: number | null;
};

/**
 * LocationAdd
 */
export type LocationAdd = {
    /**
     * Street Name
     */
    street_name?: string | null;
    /**
     * Street Number
     */
    street_number?: string | null;
    /**
     * City
     */
    city: string;
    /**
     * State Province
     */
    state_province?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * Country
     */
    country: string;
    /**
     * Located In
     */
    located_in?: string | null;
    /**
     * Lat
     */
    lat?: number | null;
    /**
     * Lon
     */
    lon?: number | null;
};

/**
 * LocationEdit
 */
export type LocationEdit = {
    /**
     * Uuid
     */
    uuid?: string | null;
    /**
     * Street Name
     */
    street_name?: string | null;
    /**
     * Street Number
     */
    street_number?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State Province
     */
    state_province?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * Country
     */
    country: string;
    /**
     * Located In
     */
    located_in?: string | null;
    /**
     * Lat
     */
    lat?: number | null;
    /**
     * Lon
     */
    lon?: number | null;
};

/**
 * Option
 */
export type Option = {
    /**
     * Number
     */
    number: number;
    /**
     * Text
     */
    text: string;
};

/**
 * PlaceAdd
 */
export type PlaceAdd = {
    /**
     * Name
     */
    name: string;
    /**
     * Lat
     */
    lat: number | string | null;
    /**
     * Lon
     */
    lon: number | string | null;
    /**
     * Lat Min
     */
    lat_min: number | string | null;
    /**
     * Lat Max
     */
    lat_max: number | string | null;
    /**
     * Lon Min
     */
    lon_min: number | string | null;
    /**
     * Lon Max
     */
    lon_max: number | string | null;
    /**
     * Population
     */
    population: number | null;
    /**
     * Importance
     */
    importance: number | null;
    /**
     * Category
     */
    category: string;
    /**
     * Region
     */
    region: string | null;
    /**
     * Country
     */
    country: string | null;
    /**
     * Language
     */
    language: string | null;
    /**
     * Geo Names
     */
    geo_names: Array<GeoNameAdd>;
};

/**
 * PlaceRoomIndexResponse
 */
export type PlaceRoomIndexResponse = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Url Slug
     */
    url_slug: string;
    /**
     * Players Min
     */
    players_min: number | null;
    /**
     * Players Max
     */
    players_max: number | null;
    /**
     * Price From
     */
    price_from: number | null;
    /**
     * Duration
     */
    duration: number | null;
    translation?: RoomTranslation | null;
};

/**
 * ReviewRequest
 */
export type ReviewRequest = {
    /**
     * Text
     */
    text: string;
    /**
     * Score
     */
    score: number;
};

/**
 * RoomAdd
 */
export type RoomAdd = {
    /**
     * Name
     */
    name: string;
    /**
     * Company Uuid
     */
    company_uuid: string;
    /**
     * Department Uuid
     */
    department_uuid?: string | null;
    /**
     * Price From
     */
    price_from?: number | null;
    /**
     * Duration
     */
    duration?: number | null;
    /**
     * Players Min
     */
    players_min?: number | null;
    /**
     * Players Max
     */
    players_max?: number | null;
    /**
     * Booking Url
     */
    booking_url?: string | null;
    difficulty?: GameDifficulty | null;
    /**
     * Category
     */
    category?: string | null;
    fear_level?: FearLevel | null;
    /**
     * Url Yt
     */
    url_yt?: string | null;
    /**
     * Lm Id
     */
    lm_id?: string | null;
    /**
     * Mt Id
     */
    mt_id?: string | null;
    /**
     * Translation
     */
    translation: Array<TranslationAdd>;
    /**
     * Supported Languages
     */
    supported_languages: Array<string>;
};

/**
 * RoomEdit
 */
export type RoomEdit = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Department Uuid
     */
    department_uuid?: string | null;
    /**
     * Price From
     */
    price_from?: number | null;
    /**
     * Game Duration
     */
    game_duration?: number | null;
    /**
     * Players Min
     */
    players_min?: number | null;
    /**
     * Players Max
     */
    players_max?: number | null;
    /**
     * Booking Url
     */
    booking_url?: string | null;
    /**
     * Lm Id
     */
    lm_id?: string | null;
    /**
     * Mt Id
     */
    mt_id?: string | null;
    /**
     * Active
     */
    active?: boolean | null;
    /**
     * Verified At
     */
    verified_at?: string | null;
    /**
     * Translation
     */
    translation?: Array<TranslationAdd> | null;
    /**
     * Supported Languages
     */
    supported_languages?: Array<string> | null;
};

/**
 * RoomIndexResponse
 */
export type RoomIndexResponse = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Url Slug
     */
    url_slug: string;
    /**
     * Booking Url
     */
    booking_url: string | null;
    /**
     * Players Min
     */
    players_min: number | null;
    /**
     * Players Max
     */
    players_max: number | null;
    /**
     * Price From
     */
    price_from: number | null;
    /**
     * Duration
     */
    duration: number | null;
    difficulty?: GameDifficulty | null;
    /**
     * Category
     */
    category?: string | null;
    fear_level?: FearLevel | null;
    /**
     * Url Yt
     */
    url_yt?: string | null;
    location: Location;
    translation?: RoomTranslation | null;
    department?: BasicDepartment | null;
    /**
     * Languages
     */
    languages?: Array<BasicLanguage> | null;
};

/**
 * RoomTranslation
 */
export type RoomTranslation = {
    /**
     * Lang
     */
    lang: string;
    /**
     * Title
     */
    title: string;
    /**
     * Lead
     */
    lead: string;
    /**
     * Description
     */
    description: string;
};

/**
 * TagAdd
 */
export type TagAdd = {
    /**
     * Room Uuid
     */
    room_uuid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * TranslationAdd
 */
export type TranslationAdd = {
    /**
     * Lang
     */
    lang: string;
    /**
     * Title
     */
    title: string;
    /**
     * Lead
     */
    lead?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WrongFeedback
 */
export type WrongFeedback = {
    /**
     * Number
     */
    number: number;
    /**
     * Feedback
     */
    feedback: string;
};

export type GetRoomsCountRoomsCountGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rooms/count';
};

export type GetRoomsCountRoomsCountGetResponses = {
    /**
     * Response Get Rooms Count Rooms Count Get
     * Successful Response
     */
    200: number;
};

export type GetRoomsCountRoomsCountGetResponse = GetRoomsCountRoomsCountGetResponses[keyof GetRoomsCountRoomsCountGetResponses];

export type GetRoomsNearbyRoomsNearbyCityNameGetData = {
    body?: never;
    path: {
        /**
         * City Name
         */
        city_name: string;
    };
    query?: never;
    url: '/rooms/nearby/{city_name}';
};

export type GetRoomsNearbyRoomsNearbyCityNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRoomsNearbyRoomsNearbyCityNameGetError = GetRoomsNearbyRoomsNearbyCityNameGetErrors[keyof GetRoomsNearbyRoomsNearbyCityNameGetErrors];

export type GetRoomsNearbyRoomsNearbyCityNameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteRoomRoomsRoomUuidDeleteData = {
    body?: never;
    path: {
        /**
         * Room Uuid
         */
        room_uuid: string;
    };
    query?: never;
    url: '/rooms/{room_uuid}';
};

export type DeleteRoomRoomsRoomUuidDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRoomRoomsRoomUuidDeleteError = DeleteRoomRoomsRoomUuidDeleteErrors[keyof DeleteRoomRoomsRoomUuidDeleteErrors];

export type DeleteRoomRoomsRoomUuidDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRoomRoomsRoomUuidDeleteResponse = DeleteRoomRoomsRoomUuidDeleteResponses[keyof DeleteRoomRoomsRoomUuidDeleteResponses];

export type GetRoomByUuidRoomsRoomUuidGetData = {
    body?: never;
    path: {
        /**
         * Room Uuid
         */
        room_uuid: string;
    };
    query?: never;
    url: '/rooms/{room_uuid}';
};

export type GetRoomByUuidRoomsRoomUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRoomByUuidRoomsRoomUuidGetError = GetRoomByUuidRoomsRoomUuidGetErrors[keyof GetRoomByUuidRoomsRoomUuidGetErrors];

export type GetRoomByUuidRoomsRoomUuidGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateRoomRoomsRoomUuidPatchData = {
    body: RoomEdit;
    path: {
        /**
         * Room Uuid
         */
        room_uuid: string;
    };
    query?: never;
    url: '/rooms/{room_uuid}';
};

export type UpdateRoomRoomsRoomUuidPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRoomRoomsRoomUuidPatchError = UpdateRoomRoomsRoomUuidPatchErrors[keyof UpdateRoomRoomsRoomUuidPatchErrors];

export type UpdateRoomRoomsRoomUuidPatchResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UpdateRoomRoomsRoomUuidPatchResponse = UpdateRoomRoomsRoomUuidPatchResponses[keyof UpdateRoomRoomsRoomUuidPatchResponses];

export type RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetData = {
    body?: never;
    path: {
        /**
         * Language
         */
        language: string;
        /**
         * Room Url Slug
         */
        room_url_slug: string;
    };
    query?: never;
    url: '/rooms/url/{language}/{room_url_slug}';
};

export type RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetError = RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetErrors[keyof RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetErrors];

export type RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetResponses = {
    /**
     * Successful Response
     */
    200: RoomIndexResponse;
};

export type RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetResponse = RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetResponses[keyof RoomByUrlSlugRoomsUrlLanguageRoomUrlSlugGetResponses];

export type RoomsByLocationRoomsUrlLanguagePlaceLocationGetData = {
    body?: never;
    path: {
        /**
         * Language
         */
        language: string;
        /**
         * Location
         */
        location: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Field
         */
        field?: 'name' | 'created_at';
        /**
         * Order
         */
        order?: 'asc' | 'desc';
    };
    url: '/rooms/url/{language}/place/{location}';
};

export type RoomsByLocationRoomsUrlLanguagePlaceLocationGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsByLocationRoomsUrlLanguagePlaceLocationGetError = RoomsByLocationRoomsUrlLanguagePlaceLocationGetErrors[keyof RoomsByLocationRoomsUrlLanguagePlaceLocationGetErrors];

export type RoomsByLocationRoomsUrlLanguagePlaceLocationGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateRoomRoomsPostData = {
    body: RoomAdd;
    path?: never;
    query?: never;
    url: '/rooms';
};

export type CreateRoomRoomsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRoomRoomsPostError = CreateRoomRoomsPostErrors[keyof CreateRoomRoomsPostErrors];

export type CreateRoomRoomsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRoomsCountTagsPostData = {
    body: TagAdd;
    path?: never;
    query?: never;
    url: '/tags';
};

export type GetRoomsCountTagsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRoomsCountTagsPostError = GetRoomsCountTagsPostErrors[keyof GetRoomsCountTagsPostErrors];

export type GetRoomsCountTagsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPlacesWithRoomsPlacesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Country
         */
        country?: string | null;
    };
    url: '/places';
};

export type GetPlacesWithRoomsPlacesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPlacesWithRoomsPlacesGetError = GetPlacesWithRoomsPlacesGetErrors[keyof GetPlacesWithRoomsPlacesGetErrors];

export type GetPlacesWithRoomsPlacesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddRoomPlacesPostData = {
    body: PlaceAdd;
    path?: never;
    query?: never;
    url: '/places';
};

export type AddRoomPlacesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddRoomPlacesPostError = AddRoomPlacesPostErrors[keyof AddRoomPlacesPostErrors];

export type AddRoomPlacesPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AddRoomPlacesPostResponse = AddRoomPlacesPostResponses[keyof AddRoomPlacesPostResponses];

export type GetCityDetailsPlacesCityAsciiNameGetData = {
    body?: never;
    path: {
        /**
         * City Ascii Name
         */
        city_ascii_name: string;
    };
    query: {
        /**
         * Language
         */
        language: string;
        /**
         * Country
         */
        country: string;
    };
    url: '/places/{city_ascii_name}';
};

export type GetCityDetailsPlacesCityAsciiNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCityDetailsPlacesCityAsciiNameGetError = GetCityDetailsPlacesCityAsciiNameGetErrors[keyof GetCityDetailsPlacesCityAsciiNameGetErrors];

export type GetCityDetailsPlacesCityAsciiNameGetResponses = {
    /**
     * Successful Response
     */
    200: CityDetailsResponse;
};

export type GetCityDetailsPlacesCityAsciiNameGetResponse = GetCityDetailsPlacesCityAsciiNameGetResponses[keyof GetCityDetailsPlacesCityAsciiNameGetResponses];

export type GetNearbyCitiesPlacesNearbyCityCityNameGetData = {
    body?: never;
    path: {
        /**
         * City Name
         */
        city_name: string;
    };
    query?: never;
    url: '/places/nearby_city/{city_name}';
};

export type GetNearbyCitiesPlacesNearbyCityCityNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetNearbyCitiesPlacesNearbyCityCityNameGetError = GetNearbyCitiesPlacesNearbyCityCityNameGetErrors[keyof GetNearbyCitiesPlacesNearbyCityCityNameGetErrors];

export type GetNearbyCitiesPlacesNearbyCityCityNameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRoomsByLocationPlacesRoomsLocationNameGetData = {
    body?: never;
    path: {
        /**
         * Location Name
         */
        location_name: string;
    };
    query?: {
        /**
         * Language
         */
        language?: string | null;
    };
    url: '/places/rooms/{location_name}';
};

export type GetRoomsByLocationPlacesRoomsLocationNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRoomsByLocationPlacesRoomsLocationNameGetError = GetRoomsByLocationPlacesRoomsLocationNameGetErrors[keyof GetRoomsByLocationPlacesRoomsLocationNameGetErrors];

export type GetRoomsByLocationPlacesRoomsLocationNameGetResponses = {
    /**
     * Response Get Rooms By Location Places Rooms  Location Name  Get
     * Successful Response
     */
    200: Array<PlaceRoomIndexResponse>;
};

export type GetRoomsByLocationPlacesRoomsLocationNameGetResponse = GetRoomsByLocationPlacesRoomsLocationNameGetResponses[keyof GetRoomsByLocationPlacesRoomsLocationNameGetResponses];

export type GetRoomsByGeolocationPlacesRoomsGeoipGetData = {
    body?: never;
    headers?: {
        /**
         * X-Forwarded-For
         */
        'x-forwarded-for'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/places/rooms/geoip';
};

export type GetRoomsByGeolocationPlacesRoomsGeoipGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRoomsByGeolocationPlacesRoomsGeoipGetError = GetRoomsByGeolocationPlacesRoomsGeoipGetErrors[keyof GetRoomsByGeolocationPlacesRoomsGeoipGetErrors];

export type GetRoomsByGeolocationPlacesRoomsGeoipGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCompaniesCompaniesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search
         */
        search?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Field
         */
        field?: 'name' | 'created_at';
        /**
         * Order
         */
        order?: 'asc' | 'desc';
    };
    url: '/companies';
};

export type GetCompaniesCompaniesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCompaniesCompaniesGetError = GetCompaniesCompaniesGetErrors[keyof GetCompaniesCompaniesGetErrors];

export type GetCompaniesCompaniesGetResponses = {
    /**
     * Successful Response
     */
    200: CompaniesPaginated;
};

export type GetCompaniesCompaniesGetResponse = GetCompaniesCompaniesGetResponses[keyof GetCompaniesCompaniesGetResponses];

export type CreateCompanyCompaniesPostData = {
    body: CompanyAdd;
    path?: never;
    query?: never;
    url: '/companies';
};

export type CreateCompanyCompaniesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCompanyCompaniesPostError = CreateCompanyCompaniesPostErrors[keyof CreateCompanyCompaniesPostErrors];

export type CreateCompanyCompaniesPostResponses = {
    /**
     * Successful Response
     */
    201: BaseUuid;
};

export type CreateCompanyCompaniesPostResponse = CreateCompanyCompaniesPostResponses[keyof CreateCompanyCompaniesPostResponses];

export type DeleteCompanyCompaniesCompanyUuidDeleteData = {
    body?: never;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/companies/{company_uuid}';
};

export type DeleteCompanyCompaniesCompanyUuidDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCompanyCompaniesCompanyUuidDeleteError = DeleteCompanyCompaniesCompanyUuidDeleteErrors[keyof DeleteCompanyCompaniesCompanyUuidDeleteErrors];

export type DeleteCompanyCompaniesCompanyUuidDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCompanyCompaniesCompanyUuidDeleteResponse = DeleteCompanyCompaniesCompanyUuidDeleteResponses[keyof DeleteCompanyCompaniesCompanyUuidDeleteResponses];

export type GetCompanyByUuidCompaniesCompanyUuidGetData = {
    body?: never;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/companies/{company_uuid}';
};

export type GetCompanyByUuidCompaniesCompanyUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCompanyByUuidCompaniesCompanyUuidGetError = GetCompanyByUuidCompaniesCompanyUuidGetErrors[keyof GetCompanyByUuidCompaniesCompanyUuidGetErrors];

export type GetCompanyByUuidCompaniesCompanyUuidGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateCompanyCompaniesCompanyUuidPatchData = {
    body: CompanyEdit;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/companies/{company_uuid}';
};

export type UpdateCompanyCompaniesCompanyUuidPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCompanyCompaniesCompanyUuidPatchError = UpdateCompanyCompaniesCompanyUuidPatchErrors[keyof UpdateCompanyCompaniesCompanyUuidPatchErrors];

export type UpdateCompanyCompaniesCompanyUuidPatchResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UpdateCompanyCompaniesCompanyUuidPatchResponse = UpdateCompanyCompaniesCompanyUuidPatchResponses[keyof UpdateCompanyCompaniesCompanyUuidPatchResponses];

export type GetCompanyDepartmentsCompaniesCompanyUuidDepartmentsGetData = {
    body?: never;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/companies/{company_uuid}/departments';
};

export type GetCompanyDepartmentsCompaniesCompanyUuidDepartmentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCompanyDepartmentsCompaniesCompanyUuidDepartmentsGetError = GetCompanyDepartmentsCompaniesCompanyUuidDepartmentsGetErrors[keyof GetCompanyDepartmentsCompaniesCompanyUuidDepartmentsGetErrors];

export type GetCompanyDepartmentsCompaniesCompanyUuidDepartmentsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteData = {
    body?: never;
    path: {
        /**
         * Department Uuid
         */
        department_uuid: string;
    };
    query?: never;
    url: '/companies/departments/{department_uuid}';
};

export type DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteError = DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteErrors[keyof DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteErrors];

export type DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteResponse = DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteResponses[keyof DeleteDepartmentCompaniesDepartmentsDepartmentUuidDeleteResponses];

export type GetDepartmentCompaniesDepartmentsDepartmentUuidGetData = {
    body?: never;
    path: {
        /**
         * Department Uuid
         */
        department_uuid: string;
    };
    query?: never;
    url: '/companies/departments/{department_uuid}';
};

export type GetDepartmentCompaniesDepartmentsDepartmentUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDepartmentCompaniesDepartmentsDepartmentUuidGetError = GetDepartmentCompaniesDepartmentsDepartmentUuidGetErrors[keyof GetDepartmentCompaniesDepartmentsDepartmentUuidGetErrors];

export type GetDepartmentCompaniesDepartmentsDepartmentUuidGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchData = {
    body: DepartmentEdit;
    path: {
        /**
         * Department Uuid
         */
        department_uuid: string;
    };
    query?: never;
    url: '/companies/departments/{department_uuid}';
};

export type UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchError = UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchErrors[keyof UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchErrors];

export type UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchResponse = UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchResponses[keyof UpdateDepartmentCompaniesDepartmentsDepartmentUuidPatchResponses];

export type CreateDepartmentCompaniesDepartmentsPostData = {
    body: DepartmentAdd;
    path?: never;
    query?: never;
    url: '/companies/departments';
};

export type CreateDepartmentCompaniesDepartmentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDepartmentCompaniesDepartmentsPostError = CreateDepartmentCompaniesDepartmentsPostErrors[keyof CreateDepartmentCompaniesDepartmentsPostErrors];

export type CreateDepartmentCompaniesDepartmentsPostResponses = {
    /**
     * Successful Response
     */
    200: BaseUuid;
};

export type CreateDepartmentCompaniesDepartmentsPostResponse = CreateDepartmentCompaniesDepartmentsPostResponses[keyof CreateDepartmentCompaniesDepartmentsPostResponses];

export type GetCompanyContactsCompaniesCompanyUuidContactsGetData = {
    body?: never;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/companies/{company_uuid}/contacts';
};

export type GetCompanyContactsCompaniesCompanyUuidContactsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCompanyContactsCompaniesCompanyUuidContactsGetError = GetCompanyContactsCompaniesCompanyUuidContactsGetErrors[keyof GetCompanyContactsCompaniesCompanyUuidContactsGetErrors];

export type GetCompanyContactsCompaniesCompanyUuidContactsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateContactCompaniesContactsPostData = {
    body: ContactAdd;
    path?: never;
    query?: never;
    url: '/companies/contacts';
};

export type CreateContactCompaniesContactsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateContactCompaniesContactsPostError = CreateContactCompaniesContactsPostErrors[keyof CreateContactCompaniesContactsPostErrors];

export type CreateContactCompaniesContactsPostResponses = {
    /**
     * Successful Response
     */
    200: BaseUuid;
};

export type CreateContactCompaniesContactsPostResponse = CreateContactCompaniesContactsPostResponses[keyof CreateContactCompaniesContactsPostResponses];

export type StartGameGamesStartPostData = {
    body: GameStart;
    path?: never;
    query?: never;
    url: '/games/start';
};

export type StartGameGamesStartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartGameGamesStartPostError = StartGameGamesStartPostErrors[keyof StartGameGamesStartPostErrors];

export type StartGameGamesStartPostResponses = {
    /**
     * Successful Response
     */
    200: GameStartResponse;
};

export type StartGameGamesStartPostResponse = StartGameGamesStartPostResponses[keyof StartGameGamesStartPostResponses];

export type GetIntroGamesIntroGameUuidGetData = {
    body?: never;
    headers?: {
        /**
         * X-Forwarded-For
         */
        'x-forwarded-for'?: string | null;
    };
    path: {
        /**
         * Game Uuid
         */
        game_uuid: string;
    };
    query?: never;
    url: '/games/intro/{game_uuid}';
};

export type GetIntroGamesIntroGameUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIntroGamesIntroGameUuidGetError = GetIntroGamesIntroGameUuidGetErrors[keyof GetIntroGamesIntroGameUuidGetErrors];

export type GetIntroGamesIntroGameUuidGetResponses = {
    /**
     * Successful Response
     */
    200: IntroResponse;
};

export type GetIntroGamesIntroGameUuidGetResponse = GetIntroGamesIntroGameUuidGetResponses[keyof GetIntroGamesIntroGameUuidGetResponses];

export type GetPuzzleGamesPuzzleGameUuidGetData = {
    body?: never;
    path: {
        /**
         * Game Uuid
         */
        game_uuid: string;
    };
    query?: never;
    url: '/games/puzzle/{game_uuid}';
};

export type GetPuzzleGamesPuzzleGameUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPuzzleGamesPuzzleGameUuidGetError = GetPuzzleGamesPuzzleGameUuidGetErrors[keyof GetPuzzleGamesPuzzleGameUuidGetErrors];

export type GetPuzzleGamesPuzzleGameUuidGetResponses = {
    /**
     * Successful Response
     */
    200: CurrentPuzzleResponse;
};

export type GetPuzzleGamesPuzzleGameUuidGetResponse = GetPuzzleGamesPuzzleGameUuidGetResponses[keyof GetPuzzleGamesPuzzleGameUuidGetResponses];

export type SubmitAnswerGamesAnswerGameUuidPostData = {
    body: AnswerRequest;
    path: {
        /**
         * Game Uuid
         */
        game_uuid: string;
    };
    query?: never;
    url: '/games/answer/{game_uuid}';
};

export type SubmitAnswerGamesAnswerGameUuidPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitAnswerGamesAnswerGameUuidPostError = SubmitAnswerGamesAnswerGameUuidPostErrors[keyof SubmitAnswerGamesAnswerGameUuidPostErrors];

export type SubmitAnswerGamesAnswerGameUuidPostResponses = {
    /**
     * Successful Response
     */
    200: AnswerResponse;
};

export type SubmitAnswerGamesAnswerGameUuidPostResponse = SubmitAnswerGamesAnswerGameUuidPostResponses[keyof SubmitAnswerGamesAnswerGameUuidPostResponses];

export type GetEndingGamesEndingGameUuidGetData = {
    body?: never;
    path: {
        /**
         * Game Uuid
         */
        game_uuid: string;
    };
    query?: never;
    url: '/games/ending/{game_uuid}';
};

export type GetEndingGamesEndingGameUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEndingGamesEndingGameUuidGetError = GetEndingGamesEndingGameUuidGetErrors[keyof GetEndingGamesEndingGameUuidGetErrors];

export type GetEndingGamesEndingGameUuidGetResponses = {
    /**
     * Successful Response
     */
    200: GameOutro;
};

export type GetEndingGamesEndingGameUuidGetResponse = GetEndingGamesEndingGameUuidGetResponses[keyof GetEndingGamesEndingGameUuidGetResponses];

export type AddReviewGamesReviewGameUuidPostData = {
    body: ReviewRequest;
    path: {
        /**
         * Game Uuid
         */
        game_uuid: string;
    };
    query?: never;
    url: '/games/review/{game_uuid}';
};

export type AddReviewGamesReviewGameUuidPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddReviewGamesReviewGameUuidPostError = AddReviewGamesReviewGameUuidPostErrors[keyof AddReviewGamesReviewGameUuidPostErrors];

export type AddReviewGamesReviewGameUuidPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AddReviewGamesReviewGameUuidPostResponse = AddReviewGamesReviewGameUuidPostResponses[keyof AddReviewGamesReviewGameUuidPostResponses];

export type LocationsSitemapSeoSitemapGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/seo/sitemap';
};

export type LocationsSitemapSeoSitemapGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RoomsSitemapSeoRoomsSitemapGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/seo/rooms_sitemap';
};

export type RoomsSitemapSeoRoomsSitemapGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetFirstUnverifiedCompanyCcCompanyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cc/company';
};

export type GetFirstUnverifiedCompanyCcCompanyGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://localhost:5000' | (string & {});
};